[book]
title = "Algorithms with TypeScript"
authors = ["Anton Moilanen"]
description = "A practical guide to data structures and algorithms for software engineers and Computer Science students"
src = "chapters"
language = "en"

[build]
build-dir = "../dist/web"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/amoilanen/Algorithms-with-TypeScript"
edit-url-template = "https://github.com/amoilanen/Algorithms-with-TypeScript/edit/master/book/chapters/{path}"
site-url = "/Algorithms-with-TypeScript/"
additional-css = []
additional-js = ["theme/fix-title.js"]

[output.html.search]
enable = true
limit-results = 30
use-hierarchical-headings = true

[output.html.fold]
enable = false

[output.html.playground]
editable = false

[output.html.print]
enable = true

[preprocessor.katex]
